name: Update releases

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: read

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  detect-changes:
    uses: ./.github/workflows/detect-changes.yaml
    secrets: inherit

  release-please:
    needs:
      - detect-changes
    if: needs.detect-changes.outputs.any == 'true'
    strategy:
      matrix:
        app: ${{ fromJSON(needs.detect-changes.outputs.affected-apps) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 23
      - id: release-please
        run: |
          npx -y github:stan-stately/release-please#stan/additional-package-paths release-pr \
            --token xxx \
            --repo-url ${{ github.repository }} \
            --config-file apps/${{ matrix.app }}/release-please-config.json \
            --manifest-file .release-please-manifest.json
